[DEVOPS-863] Добавление канала для IBM MQ (autotester), настройки - и…
BSC-RUS/AuTe-Framework pull request #10
Opened 2019-03-25 15:33 UTC by exotol

Произведенные работы: добавлено 3 новые настройки

#      amqpBroker:
#        host: 192.168.99.100
#        mqService: IBM_MQ
#        password: password
#        port: 1414
#        username: app
#        <span style="color:blue">channel: DEV.APP.SVRCONN</span>.
#        <span style="color:blue">maxTimeoutWait: 60000000</span>
#       <span style="color:blue"> useCamelNamingPolicyIbmMQ: true</span>

* выделены синим цветом
- channel  - необходима для отправки/получения сообщения при помощи MQ с вкладки Details для WebSphere MQ (иначе возникает проблема с безопасностью)
- maxTimeoutWait - максимальное время ожидания до этого было ограничено 1 минутой, по умолчианию 1 минута и остается, но в случае необходимости можно задать большее время ожиданя сообщения (определяется как min{Timeout на Details, maxTimeoutWait}
-  useCamelNamingPolicyIbmMQ - IBM_MQ требует, чтобы свойства для JMS сообщений соответствовали правилам наименования бинов. Поэтому было решено добавить возможность, аналогичную возможности в camel - конвертация ./- в символьные константы. Это позволяет обойти ряд проблем с IBM_MQ

2019-04-16 15:37 UTC, MAKAR1031 requested changes
Правильно ли я понимаю, чуть главная идея данного PR в конфигурации канала для IBM MQ?
Также, просьба исправить конфликты.

2019-04-16 15:37 UTC, MAKAR1031 commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/MqMockHelper.java
> +    public static String convertPropertyCamelPolicy(String testIdHeaderNameProperty, boolean useCamelNamingPolicy) {
Можно записать более кратко:
```java
public static String convertPropertyCamelPolicy(String headerName, boolean useCamelNaming) {
    return useCamelNaming && !StringUtils.isEmpty(headerName) ?
        headerName.replace("-", HYPHEN).replace(".", DOT) :
        headerName;
}
```

2019-04-16 15:37 UTC, MAKAR1031 commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/client/impl/mq/MqClient.java
> +    private long maxTimeoutWait = 60000L;
Можно не указывать значения полей, их значения будут заданы при выполнении конструктора.

2019-04-16 15:37 UTC, MAKAR1031 commented on atf-executor/src/main/java/ru/bsc/test/at/executor/step/executor/MqStepExecutor.java
> +    private Map<String, Object> getGeneratedProperties(Step step) {
Для чего используется заголовок, созданный этим методом?

2019-04-16 15:37 UTC, MAKAR1031 commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/MqMockHelper.java
> +    public static String convertPropertyCamelPolicy(String testIdHeaderNameProperty, boolean useCamelNamingPolicy) {
Кстати, для чего используется подобное преобразования названия заголовка?

2019-04-16 16:12 UTC, exotol commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/MqMockHelper.java
> +    public static String convertPropertyCamelPolicy(String testIdHeaderNameProperty, boolean useCamelNamingPolicy) {
> useCamelNamingPolicyIbmMQ - IBM_MQ требует, чтобы свойства для JMS сообщений соответствовали правилам наименования бинов. Поэтому было решено добавить возможность, аналогичную возможности в camel - конвертация ./- в символьные константы. Это позволяет обойти ряд проблем с IBM_MQ

У нас, например, есть поля типа x-b3-autotestid, такое поле уже не пропускается для отправки в IBM MQ  (т.к. не подходит под правила именования бинов - ibm проверяют свойства на эти правила)

2019-04-16 16:15 UTC, exotol commented on atf-executor/src/main/java/ru/bsc/test/at/executor/step/executor/MqStepExecutor.java
> +    private Map<String, Object> getGeneratedProperties(Step step) {
Там должна передаваться очередь ответов, но раньше передавался null. Получается, очередь ответов задается, но не передается как свойство, соответственно отправлять некуда. Хотя обработка далее ожидает тег для установки очереди ответа, но никогда не сможет выполнится т.е. это баг.

2019-04-23 08:01 UTC, exotol commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/MqMockHelper.java
> +    public static String convertPropertyCamelPolicy(String testIdHeaderNameProperty, boolean useCamelNamingPolicy) {
http://checkstyle.sourceforge.net/config_coding.html#AvoidInlineConditionals

дело вкуса, заменил на ваш вариант, но в целом более читаемым нахожу первый вариант, а т.к. метод сам по себе не большой, то особой нужды нет его уменьшать.

P.S. было бы не плохо, если бы вы подключили к проекту maven-checkstyle-plugin, findbugs-maven-plugin, maven-pmd-plugin и подключили систему правил. Тогда будет меньше разногласий по поводу предпочтений и практик

2019-04-23 08:03 UTC, exotol commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/client/impl/mq/MqClient.java
> +    private long maxTimeoutWait = 60000L;
Там, к сожалению, я упустил переопределение через setter, т.к. значение в 60к было по-умолчанию выполнено хардкодом, его хотелось и оставить. Это поправлю

2019-04-23 12:02 UTC, closed without merging