Fb devops 863
BSC-RUS/AuTe-Framework pull request #11
Opened 2019-04-23 12:23 UTC by exotol

Внес правки согласно комментариям и разрешил конфликты.

`      

- channel: DEV.APP.SVRCONN<br>
- maxTimeoutWait: 60000<br> 
- useCamelNamingPolicyIbmMQ: true`

Цель доработки была позволить вообще отправлять сообщения с вкладки Детали в IBM MQ и при этом указывать очередь ответов.

После поднятия версии wiremock server'a, мы обнаружили проблему (WPS-11190) при работе с мультипартом происходит NPE, т.к. отсутствует конфигурация, которую теперь выполняет jetty.

Имеется так же просьба
1) Добавить maven-pmd-plugin, findbugs-maven-plugin, maven-checkstyle-plugin и настроить список правил. И нам и вам будет удобнее писать и проверять.
2) Переносить коммиты из внутренних репозиториев в публичный при помощи pathes. 
В итоге, большая часть коммитов имеет комментарий - "Перенос из внутренннего репозитория". Имеем один коммит с кучей измененных файлов - тяжело разбираться в изменениях. Чистота в коммитах позволит лучше ориентироваться в изменениях

2019-05-14 10:13 UTC, mkurtsmanbsc requested changes
Есть два замечания.
Первое желательно поправить.
По второму уточнить, не поломается ли текущая реализация.

2019-05-14 10:13 UTC, mkurtsmanbsc commented on atf-executor/src/main/java/ru/bsc/test/at/executor/mq/IbmMqManager.java
> +        if(channel != null && !channel.isEmpty()) {
Тут лучше org.apache.commons.lang3.StringUtils.isNotEmpty

2019-05-14 10:13 UTC, mkurtsmanbsc commented on atf-executor/src/main/java/ru/bsc/test/at/executor/step/executor/requester/MqAbstractStepRequester.java
> -        ClientMQRequest clientMQRequest = new ClientMQRequest(step.getMqOutputQueueName(), requestBody, null, testId, project.getUseRandomTestId() ? project.getTestIdHeaderName() : null);
Не совсем понял такой момент, в wiremock будет отправлен project.getTestIdHeaderName() или сконвертированный ? На него завязана логика.

2019-05-14 12:41 UTC, exotol commented on atf-executor/src/main/java/ru/bsc/test/at/executor/step/executor/requester/MqAbstractStepRequester.java
> -        ClientMQRequest clientMQRequest = new ClientMQRequest(step.getMqOutputQueueName(), requestBody, null, testId, project.getUseRandomTestId() ? project.getTestIdHeaderName() : null);
Wiremock будет использовать project.getTestIdHeaderName(), измененный header используется только для отправки в MQ (у IBM MQ реализации стоит ограничение на названия свойств)

2019-05-14 12:45 UTC, exotol commented on atf-executor/src/main/java/ru/bsc/test/at/executor/mq/IbmMqManager.java
> +        if(channel != null && !channel.isEmpty()) {
Если есть объективная причина с пруфом, то я готов переписать.
На данный момент, я такой причины не вижу, код допустим. 
К тому же в проекте имеются аналогичные проверки для строк.

2019-05-22 08:59 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/application/MockApplication.java
> +        context.setAttribute(MultipartRequestConfigurer.KEY, buildMultipartRequestConfigurer());
Для чего используется данная настройка?

2019-05-22 08:59 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/application/MockApplication.java
> +    protected MultipartRequestConfigurer buildMultipartRequestConfigurer() {
Зачем выносить создание объекта в отдельный метод, ещё, к тому же, с модификатором protected?

2019-05-22 08:59 UTC, MAKAR1031 commented on atf-executor/src/main/java/ru/bsc/test/at/executor/mq/IbmMqManager.java
> +        if(channel != null && !channel.isEmpty()) {
Единственный момент - это поддержание кодовой базы в опрятном состоянии. Несомненно, есть фрагменты, которые были написаны ранее, но в планах есть привести их в порядок. Поэтому, желательно использовать рекомендованный подход к написанию.

2019-05-22 09:56 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/application/MockApplication.java
> +        context.setAttribute(MultipartRequestConfigurer.KEY, buildMultipartRequestConfigurer());
Всех нюансов уже не помню, но идея в том, что  в новой версии wiremock multipartRequestConfigurer  cоздается так multipartRequestConfigurer = (MultipartRequestConfigurer) context.getAttribute(MultipartRequestConfigurer.KEY);

а в старой - другим образом.

Поэтому данной настройки не хватает, чтобы создался multipartRequestConfigurer

2019-05-22 10:18 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/application/MockApplication.java
> +    protected MultipartRequestConfigurer buildMultipartRequestConfigurer() {
Почему protected уже не помню, для данного варианта, возможно уже не актуально.
Отдельный метод - изначально метод был фабрикой для бинов с настройками, но потом необходимость в фабрике отпала, но метод убирать не стал, т.к. не вижу чтобы он нарушал какие-то каноны. Если очень смущает protected, то могу его заменить в след. порции доработок (которые скоро залью)

2019-05-22 10:24 UTC, exotol commented
@MAKAR1031 приведите пруф, где проверка 
`  if(channel != null && !channel.isEmpty()) `
является worst practice?! я таких примеров не нашел
Будь там много условий, я бы согласился с Вами, но в данном случае увы, нет

2019-05-23 06:48 UTC, MAKAR1031 approved these changes

2019-05-27 06:48 UTC, merged