[DEVOPS-1026] Добавил флаг + конвертацию ответа в base64
BSC-RUS/AuTe-Framework pull request #19
Opened 2019-10-14 12:43 UTC by varty

[Devops 1026] Реализовать возможность сравнения изображений из ответа МкС и ожидаемого результата. https://dit.rencredit.ru/jira/browse/DEVOPS-1026

2020-02-03 13:14 UTC, MAKAR1031 commented on atf-application-ui/src/app/step-item/step-item.component.html
> +                      <b>{{'Response as base64' | translate}}</b>
При добавлении новых сообщений надо добавить текст в ресурсы для локализации:

* atf-application-ui/src/assets/i18n/en.json
* atf-application-ui/src/assets/i18n/ru.json

2020-02-11 15:56 UTC, varty commented on atf-application-ui/src/app/step-item/step-item.component.html
> +                      <b>{{'Response as base64' | translate}}</b>
Готово

2020-02-14 13:18 UTC, MAKAR1031 requested changes
Просьба поменять расположение поля "Response as base64" (http://joxi.ru/LmGGyyMuJleMYm).
Можно переместить его под "Ignore response", у которого переместить чекбокс на ту же строку.

2020-02-25 12:59 UTC, MAKAR1031 approved these changes

2020-02-25 13:00 UTC, merged