[DEVOPS-1017] Копирование заглушек
BSC-RUS/AuTe-Framework pull request #21
Opened 2019-10-14 12:45 UTC by varty

[Devops 1017] Добавлена кнопка для клонирования заглушек https://dit.rencredit.ru/jira/browse/DEVOPS-1017

2020-02-03 13:26 UTC, MAKAR1031 commented on atf-wiremock-ui/src/app/mapping-detail/mapping-detail.component.ts
> -        this.eventService.updateMappingList.next(true);
После этого изменения список заглушек продолжает обновляться после применения?

2020-02-10 10:57 UTC, MAKAR1031 requested changes
Сломалось обновление списка после применения заглушки. Просьба исправить.

2020-02-12 08:23 UTC, varty commented on atf-wiremock-ui/src/app/mapping-detail/mapping-detail.component.ts
> -        this.eventService.updateMappingList.next(true);
Вернул на место

2020-02-14 10:03 UTC, MAKAR1031 approved these changes

2020-02-14 10:04 UTC, merged