Унификация проверок запросов для MQ и WS
BSC-RUS/AuTe-Framework pull request #24
Opened 2019-11-25 12:19 UTC by varty

[DEVOPS-1362](https://dit.rencredit.ru/jira/browse/DEVOPS-1362)
По аналогии с проверкой на соответствие запроса ожидаемому сделал проверку для Jms сообщений и переложил всё это в отдельный CompareUtils класс, чтобы избежать дублирования

2020-01-31 11:14 UTC, MAKAR1031 requested changes

2020-01-31 11:14 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/mq/predicate/JmsMessagePredicateFactory.java
> +    private DocumentContext parseJson(String json){
Этот метод вернет результат отличный от `null` если строка будет содержать синтаксически корректный XML, что приведет к проблемой с JMS заглушками.

2020-01-31 11:14 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/mq/predicate/JmsMessagePredicateFactory.java
> +        return new JmsMessagePredicate(source, testId);
Может, существуют другие способы определения содержимого строки? Этот способ кажется не оптимальным.

2020-02-11 15:44 UTC, varty commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/mq/predicate/JmsMessagePredicateFactory.java
> +        return new JmsMessagePredicate(source, testId);
Похоже, что JsonPath парсит любой не json как json строку, поэтому добавил проверку через ObjectMapper jackson'а

2020-02-11 15:45 UTC, varty commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/mq/predicate/JmsMessagePredicateFactory.java
> +        return new JmsMessagePredicate(source, testId);
Договорились, что иначе никак

2020-02-14 07:15 UTC, MAKAR1031 approved these changes

2020-02-14 07:15 UTC, merged