[DEVOPS-644] Добавил вариации матчера - Request Body, добавил заполне…
BSC-RUS/AuTe-Framework pull request #8
Opened 2018-11-29 20:40 UTC by exotol

Добавил вариации матчера - Request Body, 
добавил заполнение матчера к ожидаемому запросу, чтобы исправить подсчет числа вызовов для случая вызовов на один и тот же url с разными soapaction

2018-12-04 10:27 UTC, MAKAR1031 requested changes

2018-12-04 10:27 UTC, MAKAR1031 commented on atf-application-ui/src/app/service/step.service.ts
> +import { Headers, Http } from '@angular/http';
Для чего были внесены данные изменения?

2018-12-04 10:27 UTC, MAKAR1031 commented on atf-application/src/main/java/ru/bsc/test/autotester/configuration/SpringRootConfig.java
> +        EnvironmentProperties env = YamlUtils.loadAs(new File("env.yml"), EnvironmentProperties.class);
Зачем понадобилось объявление переменной?

2018-12-04 10:27 UTC, MAKAR1031 commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/ServiceRequestsComparatorHelper.java
> +        if(isNotEmpty(request.getTypeMatching()) && isNotEmpty(request.getPathFilter())) {
Здесь неплохо было бы избавиться от дублирования и упростить код.

Например, можно добавить конструктор и метод в класс RequestMatcher:
```
public RequestMatcher(String type, String value) {
	if (TYPE_EQUAL_TO_XML.equalsIgnoreCase(type)) {
		equalToXml = value;
	} else if (TYPE_EQUAL_TO_JSON.equalsIgnoreCase(type)) {
		equalToJson = value;
	} else if (CONTAINS.equalsIgnoreCase(type)) {
		contains = value;
	} else if (XPATH.equalsIgnoreCase(type)) {
		matchesXPath = value;
	}
}

@JsonIgnore
public boolean isPresent() {
	return StringUtils.isNoneEmpty(contains, equalToJson, equalToXml, matchesXPath);
}
```

После чего использоваться просто

```
    RequestMatcher matcher = new RequestMatcher(mockServiceResponse.getTypeMatching(), mockServiceResponse.getPathFilter());
    if (matcher.isPresent()) {
        mockDefinition.getRequest().setBodyPatterns(Collections.singletonList(matcher));
    }
```

2018-12-04 10:44 UTC, exotol commented on atf-application-ui/src/app/service/step.service.ts
> +import { Headers, Http } from '@angular/http';
Прошу прощения, не обратил внимания. Среда отформатировала в соответствии со своими checkstyle'ами.

2018-12-04 10:47 UTC, exotol commented on atf-application/src/main/java/ru/bsc/test/autotester/configuration/SpringRootConfig.java
> +        EnvironmentProperties env = YamlUtils.loadAs(new File("env.yml"), EnvironmentProperties.class);
Для удобства дебага. 
Пока изучал работу кода, приходилось подменять значения в дебаге и тому подобное.

2018-12-04 10:53 UTC, exotol commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/ServiceRequestsComparatorHelper.java
> +        if(isNotEmpty(request.getTypeMatching()) && isNotEmpty(request.getPathFilter())) {
В целом, как с одним из возможных вариантов рефакторинга, согласен

2018-12-04 12:52 UTC, exotol commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/ServiceRequestsComparatorHelper.java
> +        if(isNotEmpty(request.getTypeMatching()) && isNotEmpty(request.getPathFilter())) {
Конструктор заменил на билд-метод (иначе проблемы с jackson'ом)
StringUtils.isNoneEmpty - проверяет, чтобы все были не пустые (нам не подходит), поправил условие.

2018-12-04 12:55 UTC, exotol commented on atf-application-ui/src/app/service/step.service.ts
> +import { Headers, Http } from '@angular/http';
откатил форматирование до предыдущей версии файла

2018-12-04 12:55 UTC, exotol commented on atf-application/src/main/java/ru/bsc/test/autotester/configuration/SpringRootConfig.java
> +        EnvironmentProperties env = YamlUtils.loadAs(new File("env.yml"), EnvironmentProperties.class);
Метод откатил до предыдущей версии

2018-12-04 12:55 UTC, exotol commented on atf-executor/src/main/java/ru/bsc/test/at/executor/helper/ServiceRequestsComparatorHelper.java
> +        if(isNotEmpty(request.getTypeMatching()) && isNotEmpty(request.getPathFilter())) {
Выполнил рефакторинг

2018-12-05 08:57 UTC, MAKAR1031 approved these changes

2018-12-10 08:55 UTC, merged