[DEVOPS-791] функционал по сравнению бинарных файлов при multipart
BSC-RUS/AuTe-Framework pull request #9
Opened 2019-02-20 11:53 UTC by exotol

- Добавлена возможность работы с бинарными данными
Если приходит запрос с типом multipart/, то данные в теле запроса 
можно конвертировать в base64, параметры которые присутствуют в теле таких запросов сохраняются (если были приложены), например

```
--JP_bucjXTGf4e_FWbodZlJqGcalVpZ
content-disposition=form-data; name="packageVerification"
content-type=text/plain;charset=UTF-8
content-length=1453

ew0KICAiYmF0Y2hQYXJhbWV0ZXJzIiA...
--JP_bucjXTGf4e_FWbodZlJqGcalVpZ--
```

Фильтра для конвертации вкл/выкл настройкой (в application.properties)
`multipart.filter.convert.enabled=true`

default значение false

В такой форме, данные в теле можно сравнивать.

- Байтовый  массив после преобразования в base64 имеет большой размер, 
и на некоторых строках выгоднее отключить вычисляемые значения, добавлена настройка 

```
 Do not evaluate expressions in body (вкладка Mock Requests)
```
Настройкой можно установить boundary статическим (в application.properties)
`multipart.filter.boundary.static.enabled=true`

Он будет вычисляться на основе длинны.
Добавлена настройка

`Convert base64 in multipart (Mock Responses)`
Часто необходима, чтобы сервис получал ответ в виде байтового массива (для multipart).

- (в application.properties) Так же добавлены настройки 
```
multipart.filter.threshold.tmpdir.file.size=1048576
multipart.filter.threshold.files.size=52428800
```

Размер временной директории и максимальный размер принимаемого файла, соответственно.
Значения по-умолчанию 1024 * 1024 и 50 * 1024 * 1024, соответственно

2019-03-05 12:44 UTC, MAKAR1031 requested changes

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/BinaryBase64ConvertFilter.java
> +        HttpServletResponse httpResponse = (HttpServletResponse) response;
Думаю, можно не объявлять данную переменную, response не используется как HttpServletResponse в данном методе.

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/ServletUtils.java
> +    public static MultiMap decodeUrlString(String input, String enc) {
Для чего этот метод? Я не вижу, чтобы он где-то использовался.

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/application/MockApplication.java
> +        return new BinaryBase64ConvertFilter();
Если экземпляр класса создается простым вызовом конструктора, то можно ставить аннотацию Component на класс, не создавая метода с аннотацией Bean.

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/BinaryBase64ConvertFilter.java
> +    @Value("${multipart.filter.convert.enabled:false}")
В данном случае можно создать класс, помеченный аннотацией [ConfigurationProperties](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html), который будет содержать все настройки, связанные с фильтрами, обрабатывающими multipart контент. И использовать значения этих свойств там где это необходимо, не передавая каждый раз как тут:
```
ConfigProperties configProperties = new ConfigProperties(staticBoundaryEnabled, tmpThresholdSize, filesThresholdSize);
HttpServletRequest requestWrapper = new MultipartToBase64ConverterServletRequest(httpRequest, configProperties);
```

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/MultipartToBase64ConverterServletRequest.java
> +    public static final String DEFAULT_CHARACTER_ENCODING = "utf-8";
Вместо этой константы лучше использовать `Charset.defaultCharset().name()`

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/MultipartToBase64ConverterServletRequest.java
> +    public static final String MULTIPART_TYPE    = "multipart/";
Может, вынести эту константу в класс BinaryBase64ConvertFilter и сделать её приватной?

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/ServletUtils.java
> +    public static String readText(BufferedReader reader) throws IOException {
Тот же вопрос, что и с decodeUrlString

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/ServletUtils.java
> +    public static byte[] readBytes(InputStream is) throws IOException {
Судя по коду этот метод используется в одном месте. Может его перенести в то место, где он используется и ограничить область видимости?

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-commons/src/main/java/ru/bsc/test/at/util/Constants.java
> +public class Constants {
Лучше для констант использовать enum

2019-03-05 12:44 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/ConvertedRequestBody.java
> +        final int count = rand.nextInt(11) + 30; // a random size from 30 to 40
Чем объясняется область значений для данной переменной?

2019-03-05 12:46 UTC, MAKAR1031 commented
Есть одно общее замечание, в предложенном коде достаточно много предупреждений, предлагаемых Idea, прошу обратить на них внимание, также, исправить.

2019-03-06 07:14 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/BinaryBase64ConvertFilter.java
> +        HttpServletResponse httpResponse = (HttpServletResponse) response;
Ее наличие или отсутствие не критично, так что убрал

2019-03-06 07:15 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/ServletUtils.java
> +    public static MultiMap decodeUrlString(String input, String enc) {
Да, метод не используется и остался от предыдущего варианта. Метод убрал

2019-03-06 07:25 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/application/MockApplication.java
> +        return new BinaryBase64ConvertFilter();
Если я Вас правильно понял, то Вы ожидаете вариант аналогичный 
` FilterRegistrationBean filter = new FilterRegistrationBean(new CorsFilter());`
НО!
1) Идея IC в том чтобы контейнер управлял созданием бина, если я явно создам 
BinaryBase64ConvertFilter, то он не будет управляться контейнером, а значит в нем не будет работать DI (Value/Autowired)
2) Когда я делаю так, 
` @Bean
    public Filter binaryBase64ConvertFilter() {
        return new BinaryBase64ConvertFilter();}`
то регистрирую фабрику для создания бинов и тогда будет работать DI
3) Т.е. в данном случае может заработать вариант
`    @Bean
    public FilterRegistrationBean convertFilter(BinaryBase64ConvertFilter convertFilter) {     
        FilterRegistrationBean filter = new FilterRegistrationBean(convertFilter);
        filter.addUrlPatterns("/*");
        filter.setOrder(2);
        return filter;
   }`
Бин будет создан контейнером. Для ревью я исправил на вариант 3, но в целом я не вижу особой выгоды.

2019-03-06 07:32 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/MultipartToBase64ConverterServletRequest.java
> +    public static final String DEFAULT_CHARACTER_ENCODING = "utf-8";
Переписал как StandardCharsets.UTF_8.name(), т.к. Charset.defaultCharset().name() может дать не utf-8

2019-03-06 07:33 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/MultipartToBase64ConverterServletRequest.java
> +    public static final String MULTIPART_TYPE    = "multipart/";
Вынес, сделал приватной.

2019-03-06 07:33 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/ServletUtils.java
> +    public static String readText(BufferedReader reader) throws IOException {
Остался от старой реализации, убрал метод

2019-03-06 07:34 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/ServletUtils.java
> +    public static byte[] readBytes(InputStream is) throws IOException {
Убрал класс ServletUtils, метод перенес

2019-03-06 08:05 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/utils/ConvertedRequestBody.java
> +        final int count = rand.nextInt(11) + 30; // a random size from 30 to 40
[До 70 символов в стандарте](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html)
Но есть хорошая проверенная реализация, она и была перенесена
org.apache.http.entity.mime.MultipartEntityBuilder
`private String generateBoundary()`

В целом размерность не важна для boundary

2019-03-06 08:50 UTC, exotol commented on atf-commons/src/main/java/ru/bsc/test/at/util/Constants.java
> +public class Constants {
Заменил на enum

2019-03-06 09:16 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/BinaryBase64ConvertFilter.java
> +    @Value("${multipart.filter.convert.enabled:false}")
Класс c @ConfigurationProperties я создал для свойств, но в данном случае от него профит небольшой, т.к. его можно инжектить только в spring-managed бины. 
1) BinaryBase64ConvertFilter - имеет @Component в него можно инжектить - ок.
2) MultipartToBase64ConverterServletRequest - не компонент, делать его компонентом не удобно: 

- большую часть времени не нужен
- создается на основе конкретного запроса 
- должен пересоздаваться (использую запрос)
- Если сделать компонентом MultipartToBase64ConverterServletRequest, выполнить inject d BinaryBase64ConvertFilter, то фильтр как бин не получится создать - т.к. еще нет параметра для Wrapper Request'a, а при создании бина контейнер хочет добавить зависимости.

Т.е. это становится технически сложным, если вообще возможным.
А без этого мы не можем использовать DI для ConfigProperties во Wrapper'e

**А значит нам все равно придется передать параметры**

Сильно большой большого профита в этом нет.

2019-03-06 13:29 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/application/MockApplication.java
> +        return new BinaryBase64ConvertFilter();
Я имел ввиду именно третий вариант, автоматическим созданием компонента.

2019-03-06 13:43 UTC, MAKAR1031 commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/BinaryBase64ConvertFilter.java
> +    @Value("${multipart.filter.convert.enabled:false}")
При использовании ConfigurationProperties для полей нет необходимости указывать аннотацию Value над полями. Маппинг происходит по названиям полей.
При этом значение по умолчанию указывается как начальное значение поля.
В аннотация ConfigurationProperties необходимо указать атрибут value либо prefix, прошу исправить этот момент.

Например, экземпляр подобного класса:
```
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ConfigurationProperties("multipart.filter")
@Component
public class MultipartFilterConfigProperties {
    private boolean convertEnabled = false;
    private boolean  boundaryStaticEnabled = false;
    private int thresholdTmpFileSize = 1048576;
    private int thresholdFilesSize = 52428800;
}
```
Будет сопоставлен со следующими свойствами:
```
filter.multipart.convertEnabled=...
filter.multipart.boundaryStaticEnabled=...
filter.multipart.thresholdTmpFileSize=...
filter.multipart.thresholdFilesSize=...
```

2019-03-06 13:53 UTC, MAKAR1031 requested changes
Также необходимо добавить информацию о копирайте в каждый создаваемый файл.
Шаблон находится в файле NOTICE, [идея позволяет](https://www.jetbrains.com/help/idea/copyright.html) упросить этот процесс.

2019-03-07 04:21 UTC, exotol commented on atf-wiremock/src/main/java/ru/bsc/test/at/mock/filter/BinaryBase64ConvertFilter.java
> +    @Value("${multipart.filter.convert.enabled:false}")
Внес изменения

2019-03-07 04:22 UTC, exotol commented
Добавил копирайт из NOTICE

Немного изменились названия настроек
`multipart.filter.convertEnabled=true`
`multipart.filter.boundaryStaticEnabled=true`
`multipart.filter.thresholdTmpFileSize=1048576`
`multipart.filter.thresholdFilesSize=52428800`

2019-03-07 14:10 UTC, MAKAR1031 approved these changes

2019-03-19 14:02 UTC, merged